use_frameworks!

platform :ios, '10.0'

target 'DDComponent_Example' do
  pod 'DDComponent', :path => '../'
  pod 'IBPCollectionViewCompositionalLayout'

  
  pod 'CatalogByConvention'

  target 'DDComponent_Tests' do
    inherit! :search_paths
  end
end
